name: macOS portable build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Setup Homebrew
        run: |
          brew update
          brew install opencv cmake

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release -- -j

      - name: Package artifact
        run: |
          mkdir -p artifact
          cp build/Release/simul_multi_file artifact/ || cp build/simul_multi_file artifact/
          # opzionale: copia config o risorse necessarie
          [ -f config.txt ] && cp config.txt artifact/ || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-build
          path: artifact
